// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "0x1337",
            "email": "info@kongroo.c2"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/agents/getall": {
            "get": {
                "description": "This API can be used for getting a list of all agents",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agents"
                ],
                "summary": "This API can be used for getting a list of all agents",
                "responses": {
                    "200": {
                        "description": "api response",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/reg/{agent}": {
            "post": {
                "description": "This API can be used for registering a new agent",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agent"
                ],
                "summary": "This API can be used for registering a new agent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "agent",
                        "name": "agent",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "api response",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/reg/{agent}/": {
            "get": {
                "description": "This API can be used for getting agents specs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agent"
                ],
                "summary": "This API can be used for getting agents specs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "agent",
                        "name": "agent",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "api response",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/tasks/{agent}": {
            "get": {
                "description": "This API can be used for getting task for ana gent",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "This API can be used for getting task for an agent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "agent",
                        "name": "agent",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "api response",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "This API can be used for sending output of previously executed command",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "This API can be used for sending output of previously executed command",
                "responses": {
                    "200": {
                        "description": "api response",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/tasks/{agent}/history": {
            "get": {
                "description": "This API can be used for getting history for a specific agent",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task",
                    "Agent"
                ],
                "summary": "This API can be used for getting history for a specific agent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "agent",
                        "name": "agent",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "api response",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/tasks/{agent}/{task}": {
            "post": {
                "description": "This API can be used for creating a new task for ana gent",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "This API can be used for creating a new task for ana gent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "agent in charge to run command",
                        "name": "agent",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "base64 command",
                        "name": "task",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "api response",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Kongroo-C2 APIs docs",
	Description:      "kongroo-c2 documentation for APIs",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
